name: ecache
version: 2.1.0
description: >
  Provide a dart cache library usable on web, flutter and server side
homepage: https://github.com/mikes222/ecache
environment:
  # 2.17 needed for weakreference
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  #

dev_dependencies:

  lints: ^6.0.0

  # BSD-3
  test: ^1.26.3