name: ecache
version: 2.0.4
description: >
  Provide a dart cache library usable on web, flutter and server side
homepage: https://github.com/mikes222/ecache
environment:
  # 2.17 needed for weakreference
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

